

baseURL: "https://rdnaidu.com"
title: "Dhanu N Joy — Java Developer"
footnoteReturnLinkContents: "↩"
permalinks:
  articles: /article/:slug/
  article-resources: /article/:slug/resources/
params:
  Description: "Hey there, I'm Dhanu N Joy, a java developer who enjoys testing everything."
  AuthorName: "Dhanu N Joy"
  GitHubUser: "iamrdn"
  images: ["/img/julian-signature-blue.jpg"]

taxonomies:
  tag: "tags"
  category: "categories"

blackfriday:
 hrefTargetBlank: true

social: 
  facebook_app_id: "275156446240779"
  twitter: "@iamrdn_"
